"""Add score to message

Revision ID: ee1f6582eef0
Revises: d18ddd431d71
Create Date: 2023-03-01 14:38:20.994667

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "ee1f6582eef0"
down_revision = "d18ddd431d71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "worker_compliance_check",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("worker_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("compare_worker_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("responded", sa.Boolean(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["compare_worker_id"],
            ["worker.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["worker.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_worker_compliance_check_compare_worker_id"),
        "worker_compliance_check",
        ["compare_worker_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_worker_compliance_check_worker_id"), "worker_compliance_check", ["worker_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_worker_compliance_check_worker_id"), table_name="worker_compliance_check")
    op.drop_index(op.f("ix_worker_compliance_check_compare_worker_id"), table_name="worker_compliance_check")
    op.drop_table("worker_compliance_check")
    # ### end Alembic commands ###
