"""add_active_messsage_id_and_inferior_drafts

Revision ID: aeaf37fb5822
Revises: 5b4211625a9f
Create Date: 2023-05-13 20:38:44.114043

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "aeaf37fb5822"
down_revision = "5b4211625a9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("active_message_id", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("message", sa.Column("inferior_drafts", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "inferior_drafts")
    op.drop_column("chat", "active_message_id")
    # ### end Alembic commands ###
