"""initial commit

Revision ID: 3a4cd8777eb2
Revises:
Create Date: 2023-02-10 02:21:27.086772

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3a4cd8777eb2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat",
        sa.Column("conversation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pending_message_request", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("message_request_state", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chat")
    # ### end Alembic commands ###
