"""changed compliance check field

Revision ID: 23651ab20341
Revises: cd45aaf5b42c
Create Date: 2023-03-08 22:38:57.748534

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "23651ab20341"
down_revision = "cd45aaf5b42c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("worker", sa.Column("in_compliance_check_since", sa.DateTime(), nullable=True))
    op.drop_column("worker", "in_compliance_check")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "worker",
        sa.Column(
            "in_compliance_check", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("worker", "in_compliance_check_since")
    # ### end Alembic commands ###
