"""add_sibling_active_and_inferior_drafts_to_message

Revision ID: 3eca7b92b91a
Revises: 5b4211625a9f
Create Date: 2023-05-13 13:54:06.418391

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3eca7b92b91a"
down_revision = "5b4211625a9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("active_sibling", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("message", sa.Column("inferior_drafts", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "inferior_drafts")
    op.drop_column("message", "active_sibling")
    # ### end Alembic commands ###
