"""add_sibling_active_to_message

Revision ID: 19178d144265
Revises: 5b4211625a9f
Create Date: 2023-05-07 09:23:31.475254

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "19178d144265"
down_revision = "5b4211625a9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("active_sibling", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "active_sibling")
    # ### end Alembic commands ###
