"""Add score to message

Revision ID: 0f89c99ffdc8
Revises: a2865908a537
Create Date: 2023-03-01 14:42:18.577510

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0f89c99ffdc8"
down_revision = "a2865908a537"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_vote_message_id", table_name="vote")
    op.drop_table("vote")
    op.add_column("message", sa.Column("score", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "score")
    op.create_table(
        "vote",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("message_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["message.id"], name="vote_message_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="vote_pkey"),
    )
    op.create_index("ix_vote_message_id", "vote", ["message_id"], unique=False)
    # ### end Alembic commands ###
