"""Add users table

Revision ID: 6aca102423d4
Revises: 1583e3827f50
Create Date: 2023-02-21 18:51:24.418325
"""

from uuid import uuid4

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "6aca102423d4"
down_revision = "1583e3827f50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), default=str(uuid4()), nullable=False),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sa.String(256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_provider_provider_account_id"), "provider", ["provider_account_id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_provider_provider_account_id"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
