"""nullable field

Revision ID: cd45aaf5b42c
Revises: 0f89c99ffdc8
Create Date: 2023-03-07 23:07:27.871037

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd45aaf5b42c"
down_revision = "0f89c99ffdc8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("worker_compliance_check", "compare_worker_id", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("worker_compliance_check", "compare_worker_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
