"""initial commit

Revision ID: 1583e3827f50
Revises:
Create Date: 2023-02-17 23:54:21.890186

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1583e3827f50"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat", sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.PrimaryKeyConstraint("id")
    )
    op.create_table(
        "worker",
        sa.Column("in_compliance_check", sa.Boolean(), server_default=sa.text("false"), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("api_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("next_compliance_check", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_worker_api_key"), "worker", ["api_key"], unique=False)
    op.create_table(
        "message",
        sa.Column("work_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("worker_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("chat_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("state", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("work_begin_at", sa.DateTime(), nullable=True),
        sa.Column("work_end_at", sa.DateTime(), nullable=True),
        sa.Column("worker_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("worker_compat_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["chat_id"],
            ["chat.id"],
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["worker.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_chat_id"), "message", ["chat_id"], unique=False)
    op.create_index(op.f("ix_message_role"), "message", ["role"], unique=False)
    op.create_index(op.f("ix_message_worker_compat_hash"), "message", ["worker_compat_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_worker_compat_hash"), table_name="message")
    op.drop_index(op.f("ix_message_role"), table_name="message")
    op.drop_index(op.f("ix_message_chat_id"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_worker_api_key"), table_name="worker")
    op.drop_table("worker")
    op.drop_table("chat")
    # ### end Alembic commands ###
