"""added modified to chat

Revision ID: b247f202e522
Revises: af8668441ff0
Create Date: 2023-03-12 17:36:53.061631

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b247f202e522"
down_revision = "af8668441ff0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("modified_at", sa.DateTime(), nullable=False))
    op.create_index(op.f("ix_chat_modified_at"), "chat", ["modified_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_modified_at"), table_name="chat")
    op.drop_column("chat", "modified_at")
    # ### end Alembic commands ###
