"""added created and title to chat

Revision ID: af8668441ff0
Revises: 486fe9e7fb84
Create Date: 2023-03-12 17:35:27.837252

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "af8668441ff0"
down_revision = "486fe9e7fb84"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("chat", sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f("ix_chat_created_at"), "chat", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_created_at"), table_name="chat")
    op.drop_column("chat", "title")
    op.drop_column("chat", "created_at")
    # ### end Alembic commands ###
