"""added name field

Revision ID: 4b846e7314b4
Revises: 569cd595bb10
Create Date: 2023-02-11 01:51:16.288860

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b846e7314b4"
down_revision = "569cd595bb10"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("worker", sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("worker", "name")
    # ### end Alembic commands ###
