model_name: facebook/galactica-125m
freeze_layer: 10
learning_rate: 1e-5
gradient_checkpointing: false
gradient_accumulation_steps: 32
per_device_train_batch_size: 2
warmup_steps: 600
save_steps: 100
max_length: 512
num_train_epochs: 2
datasets:
  - webgpt
  - hfsummary
