# This docker file will update the web database with schema changes.  Later it
# will be updated to do prisma migrations.

FROM --platform=linux/amd64 node:16.18.0 AS runner

WORKDIR /app

COPY ./website/ .

CMD ["npx", "prisma", "db", "push"]
