{
 "title": "OA Inference",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Inference Uptime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(\r\n  (\r\n    sum without() (up{job=~\"$job\"})\r\n      or\r\n    (0 * sum_over_time(up{job=~\"$job\"}[24h]))\r\n  )[24h:5m]\r\n)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Success Rate By Endpoint [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  sum(increase(http_requests_total{status=\"2xx\", job=~\"$job\"}[5m])) by (handler)\n    /\n  sum(increase(http_requests_total{job=~\"$job\"}[5m])) by (handler)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Response Time By Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=~\"$job\",handler!=\"none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Unsuccessful Requests By Endpoint [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=~\"$job\", status!=\"2xx\"}[5m])",
     "legendFormat": "{{handler}}({{method}})"
    }
   ]
  },
  {
   "title": "Successful Requests By Endpoint [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(http_requests_total{job=~\"$job\", status=\"2xx\"}[5m])",
     "legendFormat": "{{handler}}({{method}})"
    }
   ]
  },
  {
   "title": "Requests [5m]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{job=~\"$job\"}[5m])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "http_request_duration heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "sum by(le) (rate(http_request_duration_seconds_bucket{job=~\"$job\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}