# -*- coding: utf-8 -*-
"""add deleted field to post

Revision ID: 6cb49da61b74
Revises: 73ce3675c1f5
Create Date: 2022-12-30 06:54:47.110204

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6cb49da61b74"
down_revision = "73ce3675c1f5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("post", sa.Column("deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("post", "deleted")
    # ### end Alembic commands ###
