"""Add stats_enabled field to User

Revision ID: a66a3d79dc80
Revises: 0964ac95170d
Create Date: 2023-01-16 23:15:28.294111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66a3d79dc80'
down_revision = '0964ac95170d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('stats_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'stats_enabled')
    # ### end Alembic commands ###
