"""added root tokens for adding api clients

Revision ID: 4bcce664bdf9
Revises: 423557e869e4
Create Date: 2023-01-15 15:12:29.381182

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "4bcce664bdf9"
down_revision = "0964ac95170d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_client", sa.Column("added_by_root_token", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("api_client", "added_by_root_token")
    # ### end Alembic commands ###
