"""add origin column to message

Revision ID: 014291edf55c
Revises: f856bf19d32b
Create Date: 2023-01-28 01:09:56.206507

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "014291edf55c"
down_revision = "f856bf19d32b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("origin", sa.String(length=1024), server_default="oasst_user", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "origin")
    # ### end Alembic commands ###
