"""add_message_revisions

Revision ID: e3dfe82545f4
Revises: 1b6e3ae16e9d
Create Date: 2023-06-02 16:08:10.545377

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e3dfe82545f4"
down_revision = "1b6e3ae16e9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_revision",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("message_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_date", sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False
        ),
        sa.Column("previous_revision_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["message.id"],
        ),
        sa.ForeignKeyConstraint(
            ["previous_revision_id"],
            ["message_revision.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("message", sa.Column("previous_revision_id", sqlmodel.sql.sqltypes.GUID(), nullable=True))
    op.drop_index("idx_search_vector", table_name="message")
    op.create_index("ix_search_vector", "message", ["search_vector"], unique=False, postgresql_using="gin")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_search_vector", table_name="message", postgresql_using="gin")
    op.create_index("idx_search_vector", "message", ["search_vector"], unique=False)
    op.drop_column("message", "previous_revision_id")
    op.drop_table("message_revision")
    # ### end Alembic commands ###
