"""add skip bool & skip_reason to task

Revision ID: 9e7ec4a9e3f2
Revises: 7b8f0011e0b0
Create Date: 2023-02-01 21:46:49.971052

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9e7ec4a9e3f2"
down_revision = "7b8f0011e0b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("skipped", sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column("task", sa.Column("skip_reason", sqlmodel.sql.sqltypes.AutoString(length=515), nullable=True))
    op.drop_column("user_stats", "streak_last_day_date")
    op.drop_column("user_stats", "streak_days")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_stats", sa.Column("streak_days", sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(
        "user_stats", sa.Column("streak_last_day_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True)
    )
    op.drop_column("task", "skip_reason")
    op.drop_column("task", "skipped")
    # ### end Alembic commands ###
