"""add lang to task model

Revision ID: c5430c8c9859
Revises: 2a492eaaa630
Create Date: 2023-05-10 22:20:19.246049

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "c5430c8c9859"
down_revision = "2a492eaaa630"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("lang", sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "lang")
    # ### end Alembic commands ###
