"""Add ai_model field and index to User model

Revision ID: 2a492eaaa630
Revises: 9db92d504f64
Create Date: 2023-05-04 14:50:33.079150

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a492eaaa630"
down_revision = "9db92d504f64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("ai_model", sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.create_index("ix_ai_model", "user", ["ai_model"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ai_model", table_name="user")
    op.drop_column("user", "ai_model")
    # ### end Alembic commands ###
