"""Add search vector update date, indexes

Revision ID: d18213c629be
Revises: c181661eba3a
Create Date: 2023-06-11 15:44:49.911455

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d18213c629be"
down_revision = "c181661eba3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("message", sa.Column("search_vector_update_date", sa.DateTime(timezone=True), nullable=True))
    op.create_index(
        op.f("ix_message_search_vector_update_date"), "message", ["search_vector_update_date"], unique=False
    )
    op.create_index(op.f("ix_message_revision_created_date"), "message_revision", ["created_date"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_revision_created_date"), table_name="message_revision")
    op.drop_index(op.f("ix_message_search_vector_update_date"), table_name="message")
    op.drop_column("message", "search_vector_update_date")
    # ### end Alembic commands ###
