"""Add visible_in_public_leaderboards column

Revision ID: 2c93612eab47
Revises:
Create Date: 2023-01-26 21:38:44.384491

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2c93612eab47"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("visible_in_public_leaderboards", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "visible_in_public_leaderboards")
    # ### end Alembic commands ###
