version: "3.7"

services:
  # This DB is for the FastAPI Backend.
  db:
    extends:
      file: ../frontend-development/docker-compose.yaml
      service: db

  # This DB is for Web Authentication and data caching.
  webdb:
    extends:
      file: ../frontend-development/docker-compose.yaml
      service: webdb

  # This lets you manually inspect the web and backend databases.
  adminer:
    extends:
      file: ../frontend-development/docker-compose.yaml
      service: adminer

  # This fakes an SMTP email server used by website authentication.
  # User registration emails can be found by going to localhost:1080 and
  # opening the emails listed.
  maildev:
    extends:
      file: ../frontend-development/docker-compose.yaml
      service: maildev

  # The oassist backend service.
  backend:
    extends:
      file: ../frontend-development/docker-compose.yaml
      service: backend

  # The oassist web service.
  web:
    build:
      dockerfile: docker/Dockerfile.website
      context: ../../
    image: oasst-web
    environment:
      - DATABASE_URL=postgres://postgres:postgres@webdb/ocgpt_website
      - FASTAPI_URL=http://backend:8080
      - FASTAPI_KEY=1234
      - NEXTAUTH_SECRET=O/M2uIbGj+lDD2oyNa8ax4jEOJqCPJzO53UbWShmq98=
      - EMAIL_SERVER_HOST=maildev
      - EMAIL_SERVER_PORT=1025
      - EMAIL_FROM=info@example.com
      - NEXTAUTH_URL=http://localhost:3000
    depends_on:
      webdb:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: bash wait-for-postgres.sh node server.js
