name: Build Inference Images

on:
  push:
    branches:
      - main
    paths:
      - docker/inference/**
      - inference/**

jobs:
  build-inference-server:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image-name: oasst-inference-server
      context: .
      dockerfile: docker/inference/Dockerfile.server
      build-args: ""
  build-inference-worker-full:
    uses: ./.github/workflows/docker-build.yaml
    with:
      image-name: oasst-inference-worker-full
      context: .
      dockerfile: docker/inference/Dockerfile.worker-full
      build-args: ""