name: Deploy docs to gitHub pages

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/deploy-docs-site.yaml"
      - "docs/**"
  pull_request:
    paths:
      - ".github/workflows/deploy-docs-site.yaml"
      - "docs/**"

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Setup yarn
        run:
          corepack enable && corepack prepare yarn@stable --activate && mkdir
          ~/.yarn

      - id: yarn-cache-dir-path
        name: Get yarn cache directory path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
        working-directory: docs

      - name: Restore yarn cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key:
            yarn-cache-folder-${{ hashFiles('docs/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-

      - run: yarn install --immutable
      - run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
