name: Website Tests (Cypress)

on:
  push:
    branches:
      - main
    paths:
      - website/**
  pull_request:
    paths:
      - website/**

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Start server in the background
        run: docker compose up -d
      - name: Cypress run
        uses: cypress-io/github-action@v5.0.2
        with:
          browser: chrome
          working-directory: website
